library/book/urls.py
from django.contrib import admin
from django.urls import path
from book import views
app_name="book"


urlpatterns = [
    path('',views.home,name="home"),
    path('add/',views.add,name="add"),
    path('view',views.view,name="view"),
    path('viewbook/<int:p>',views.viewbook,name="viewbook"),
    path('deletebook/<int:p>',views.deletebook,name="deletebook"),
    path('editbook/<int:p>',views.editbook,name="editbook"),
]

library/library/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('book.urls')),
    path('students/',include('students.urls')),
]
if settings.DEBUG:
         urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

library/students/urls.py
from django.contrib import admin
from django.urls import path
from students import views
app_name="students"
urlpatterns = [
    path('register',views.register,name="register"),
    path('login',views.user_login,name="user_login"),
    path('logout',views.user_logout,name="user_logout"),
    path('studentdetails',views.studentdetails,name="studentdetails"),
    path('addstudent',views.addstudent,name="addstudent"),
]

library/book/models.py
from django.db import models

# Create your models here.
class Book(models.Model):
    title=models.CharField(max_length=20)
    author=models.CharField(max_length=20)
    price=models.IntegerField()
    pdf=models.FileField(upload_to="book/pdf")
    image=models.ImageField(upload_to="book/cover",null=True,blank=True)

    def __str__(self):
        return self.title

library/students/models.py
from django.db import models

# Create your models here.
class student(models.Model):
    name=models.CharField(max_length=20)
    age=models.IntegerField()
    place=models.CharField(max_length=20)
    def __str__(self):
        return self.name

library/book/forms.py
from django import forms
from book.models import Book

class BookForm(forms.ModelForm):

    class Meta:

        model=Book

        fields='__all__'


        # or
        # fields=['title','price']
        # or
        # exclude=['author']

library/book/views.py
from django.shortcuts import render
from book.models import Book
from book.forms import BookForm
from django.contrib.auth.decorators import login_required
# Create your views here.

def home(request):
    return render(request,'home.html')

@login_required
def add(request):
    if(request.method=="POST"):
        t=request.POST['t']
        a=request.POST['a']
        p= request.POST['p']
        f=request.FILES['f']
        i=request.FILES['i']
        b=Book.objects.create(title=t,author=a,price=p,pdf=f,image=i)
        b.save()
        return view(request)
    return render(request,'add.html')

# def add(request):
#     if(request.method=="POST"):
#         form=BookForm(request.POST)
#         if form.is_valid():
#             form.save()
#             return view(request)
#     form=BookForm()
#     return render(request,'add1.html',{'form':form})
@login_required
def view(request):
    b=Book.objects.all()
    return render(request,'view.html',{'book':b})
@login_required
def viewbook(request,p):
    b=Book.objects.get(id=p)
    return render(request,'viewbook.html',{'b':b})
@login_required
def deletebook(request,p):
    b=Book.objects.get(id=p)
    b.delete()
    return view(request)

@login_required
def editbook(request,p):
    b=Book.objects.get(id=p)
    if(request.method == "POST"):
      form=BookForm(request.POST,request.FILES,instance=b)
      if form.is_valid():
         form.save()
         return view(request)

    form=BookForm(instance=b)

    return render(request,'edit.html',{'f':form})

library/students/views.py
from django.shortcuts import render,redirect
from students.models import student
from django.contrib.auth.models import User
from django.contrib.auth import authenticate,login,logout
from django.contrib import messages
from django.contrib.auth.decorators import login_required


# Create your views here.

def register(request):
    if(request.method=="POST"):
        u=request.POST['u']
        p=request.POST['p']
        p1= request.POST['p1']
        e= request.POST['e']
        f=request.POST['f']
        l=request.POST['l']
        if(p==p1):
            u=User.objects.create_user(username=u,password=p,email=e,first_name=f,last_name=l)
            u.save()
            return redirect('book:home')
    return render(request,'register.html')

def user_login(request):
    if(request.method=="POST"):
        u=request.POST['u']
        p=request.POST['p']
        user=authenticate(username=u,password=p)
        if user:
            login(request,user)
            return redirect('book:home')
        else:
            return messages.error(request,"Invalid credentials")

    return render(request,'login.html')
@login_required
def user_logout(request):
    logout(request)
    return user_login(request)
@login_required
def studentdetails(request):
    s=student.objects.all()
    return render(request,'studentdetails.html',{'st':s})
@login_required
def addstudent(request):
    if (request.method == "POST"):
        n=request.POST['n']
        a=request.POST['a']
        p=request.POST['p']
        s=student.objects.create(name=n,age=a,place=p)
        s.save()
        return studentdetails(request)
    return render(request, 'addstudent.html')

library/templates/add.html
<!DOCTYPE html>
{% extends 'base.html' %}

{% load static %}
{% block content %}
<h2>ADD BOOKS</h2>

<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
<div class="mb-3">
  <label  class="form-label">TITLE</label>
  <input type="text"  class="form-control"  name="t" placeholder="enter title">
</div>
    <div class="mb-3">
  <label  class="form-label">AUTHOR</label>
  <input type="text" class="form-control" name="a" placeholder="enter author name">
</div>
    <div class="mb-3">
  <label  class="form-label">PRICE</label>
  <input type="number" class="form-control" name="p" placeholder="enter amount">
</div>
    <div class="mb-3">
  <label  class="form-label">PDF</label>
  <input type="file" class="form-control" name="f">
</div>
    <div class="mb-3">
  <label  class="form-label">IMAGE</label>
  <input type="file" class="form-control" name="i">
</div>
    <div class="mb-3">

  <input type="submit" class="form-control">
</div>

    </form>

{% endblock %}

library/templates/add1.html
<!DOCTYPE html>
{% extends 'base.html' %}

{% load static %}
{% block content %}
<h2>ADD BOOKS</h2>
<form method="POST">
  {% csrf_token %}
<table>
{{form.as_table}}
</table>
  <input type="submit">
  </form>
{% endblock %}

library/templates/addstudent.html
<!DOCTYPE html>
{% extends 'base.html' %}

{% load static %}
{% block content %}
<h2>ADD STUDENT</h2>

<form method="POST">
    {% csrf_token %}
<div class="mb-3">
  <label  class="form-label">STUDENT NAME</label>
  <input type="text"  class="form-control"  name="n" placeholder="enter name">
</div>
    <div class="mb-3">
  <label  class="form-label">STUDENT AGE</label>
  <input type="NUMBER" class="form-control" name="a" placeholder="enter age">
</div>
    <div class="mb-3">
  <label  class="form-label">PLACE</label>
  <input type="text" class="form-control" name="p" placeholder="enter place">
</div>
    <div class="mb-3">

  <input type="submit" class="form-control">
</div>

    </form>

{% endblock %}

library/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
   <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
   <link rel="stylesheet" href="{% static 'css/a.css' %}">

</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-secondary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">LIBRARY</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'book:home' %}">Home</a>
        </li>
        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'book:add' %}">ADD BOOKS</a>
        </li>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'book:view' %}">VIEW BOOKS</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'students:studentdetails' %}">STUDENT DETAILS</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'students:addstudent' %}">ADD+STUDENT</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'students:user_logout' %}">LOGOUT</a>
        </li>
        {% else %}
          <li class="nav-item">
          <a class="nav-link" href="{% url 'students:register' %}">REGISTER</a>
        </li>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'students:user_login' %}">LOGIN</a>
        </li>
        {% endif %}


      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search Book</button>
      </form>
    </div>
  </div>
</nav>
{% block content %}
{% endblock %}


</body>
</html>

library/templates/edit.html
<!DOCTYPE html>
{% extends 'base.html' %}

{% load static %}
{% block content %}
<h2>EDIT BOOKS</h2>
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <table>
        {{f.as_table}}
    </table>
    <input type="submit">
</form>
{% endblock %}

library/templates/home.html
<!DOCTYPE html>
{% extends 'base.html' %}

{% load static %}
{% block content %}
<h2>WELCOME TO HOME</h2>
{% if user.is_authenticated %}
{{user.username}}
{% else %}
<p>gust</p>
{% endif %}
{% endblock %}

library/templates/login.html
<!DOCTYPE html>
{% extends 'base.html' %}

{% load static %}
{% block content %}
<h2>LOGIN</h2>
<form method="POST" >
    {% csrf_token %}
<div class="mb-3">
  <label  class="form-label">USER NAME:</label>
  <input type="text"  class="form-control"  name="u" placeholder="enter username">
</div>
    <div class="mb-3">
  <label  class="form-label">PASSWORD:</label>
  <input type="password" class="form-control" name="p" placeholder="enter password">
</div>
    <div class="mb-3">
        <input type="submit" class="form-control">
</div>
</form>
{% if messages %}
<ul>
    {% for msg in messages %}
    <li>{{msg}}</li>
    {% endfor %}

</ul>
{% endif %}
{% endblock %}

library/templates/register.html
<!DOCTYPE html>
{% extends 'base.html' %}

{% load static %}
{% block content %}
<h2>REGISTER</h2>
<form method="POST" >
    {% csrf_token %}
<div class="mb-3">
  <label  class="form-label">USER NAME:</label>
  <input type="text"  class="form-control"  name="u" placeholder="enter username">
</div>
    <div class="mb-3">
  <label  class="form-label">PASSWORD:</label>
  <input type="password" class="form-control" name="p" placeholder="enter password">
</div>
    <div class="mb-3">
  <label  class="form-label">CONFORM PASSWORD:</label>
  <input type="password" class="form-control" name="p1" placeholder="enter password">
</div>
    <div class="mb-3">
  <label  class="form-label">FIRST NAME:</label>
  <input type="text" class="form-control" name="f" placeholder="enter firstname">
</div>
    <div class="mb-3">
  <label  class="form-label">LAST NAME:</label>
  <input type="text" class="form-control" name="l" placeholder="enter last name">
</div>
    <div class="mb-3">
  <label  class="form-label">EMAIL ID:</label>
  <input type="email" class="form-control" name="e" placeholder="enter email id">
</div>
    <div class="mb-3">
        <input type="submit" class="form-control">
</div>
</form>
{% endblock %}

library/templates/studentdetails.html
<!DOCTYPE html>
{% extends 'base.html' %}

{% load static %}
{% block content %}
<h2>VIEW student details</h2>
<ol>
    {% for i in st %}
    <li>Student Details</li>
    <ul>
        <li>{{i.name}}</li>
        <li>{{i.age}}</li>
        <li>{{i.place}}</li>
    </ul>
    {% endfor %}
</ol>

{% endblock %}

library/templates/view.html
<!DOCTYPE html>
{% extends 'base.html' %}

{% load static %}
{% block content %}
<h2>VIEW BOOKS</h2>
<table class="table table-bordered">
    <tr>
        <th>TITLE</th>
        <th>AUTHOR</th>
        <th>PRICE</th>
        <th>IMAGE</th>
        <th>DOCUMENT</th>
        <th>VIEW</th>
        <th>EDIT</th>
        <th>DELETE</th>
    </tr>
    {% for i in book %}
    <tr>
        <td>{{i.title}}</td>
        <td>{{i.author}}</td>
        <td>{{i.price}}</td>
        <td><img src="{{i.image.url}}"></td>
        <td><a href="{{i.pdf.url}}">download</a></td>
        <td><a class="btn btn-danger" href="{% url 'book:viewbook' i.id %}">VIEW</a></td>
        <td><a class="btn btn-danger" href="{% url 'book:editbook' i.id %}">EDIT</a></td>
        <td><a class="btn btn-danger" href="{% url 'book:deletebook' i.id %}">DELETE</a></td>
    </tr>
    {% endfor %}
</table>

<!--<ol>-->
<!--    {% for i in book %}-->
<!--    <li>Book Details</li>-->
<!--    <ul type="disc">-->
<!--        <li>Title:{{i.title}}</li>-->
<!--        <li>Author:{{i.author}}</li>-->
<!--        <li>Price:{{i.price}}</li>-->

<!--    </ul>-->
<!--    {% endfor %}-->
<!--</ol>-->
{% endblock %}

library/templates/viewbook.html
<!DOCTYPE html>


{% extends 'base.html' %}

{% load static %}
{% block content %}
<h2>VIEW BOOKS DETAILS</h2>
<center>
<table class="table table-bordered">
    <tr>
        <th>cover</th><td><img src="{{b.image.url}}"></td></tr>
       <tr> <th>title</th><td>{{b.title}}</td></tr>
       <tr><th>author</th><td>{{b.author}}</td></tr>
       <tr><th>price</th><td>{{b.price}}</td></tr>
       <tr><th>document</th><td><a href="{{b.pdf.url}}">DOWNLOAD</a></td>
    </tr>

</table>
</center>

{% endblock %}